\import IO.Base
\import IO.Meta
\import IO.Meta.Strings
\import IO.Files

\func execution => unsafePerformIO
    (print "arend.yaml")

\func execution2 => unsafePerformIO
    (readFile (fileInProject "arend.yaml") >>= print)

\func execution3 => unsafePerformIO
    (readFile (fileInProject "arend-io.iml") >>= print)

\func execution4 => unsafePerformIO
    (print projectRoot)

\func execution5 => unsafePerformIO
    (readProc "java --version" >>= print)

\func execution6 => unsafePerformIO
    (readProc "javac --version" >>= print)
