\import IO.Base
\import IO.FakeString
\import IO.Meta
\import IO.Meta.Paths
\import IO.Meta.Strings

\func execution => performIO
    (print arendYAML)

\func execution2 => performIO
    (readFile arendYAML >>= print)

\func execution3 => performIO
    (readFile arendIoIml >>= print)

\func execution4 => performIO
    (print projectRoot)

\func execution5 => performIO
    (readProc (java ++ space ++ --version) >>= print)
