name: check
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: [11]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        path: arend-io
    - uses: actions/checkout@v2
      with:
        repository: JetBrains/Arend
        path: Arend
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - uses: eskatos/gradle-command-action@v1
      with:
        wrapper-cache-enabled: false
        build-root-directory: arend-io/meta
        wrapper-directory: arend-io/meta
        arguments: classes --info --no-daemon --stacktrace
    - uses: suisei-cn/actions-download-file@v1
      id: downloadfile
      with:
        url: "https://github.com/JetBrains/Arend/releases/download/v1.5.0/Arend.jar"
        target: .
    - run: java -jar Arend.jar arend.yaml
